-- Sakila Sample Database Schema for Oracle 23ai
-- Version 1.2

-- Copyright (c) 2006, 2019, Oracle and/or its affiliates.
-- All rights reserved.
-- BSD License (see mysql/1-sakila-schema.sql for full text).

-- Hand-ported from mysql/1-sakila-schema.sql.
-- Run as the sakila application user against FREEPDB1.
-- All objects are owned by the sakila user (the schema is the user).

-- Notes on omissions (consistent with sakiladb/clickhouse):
--   - film_text table (MySQL FULLTEXT helper).
--   - All triggers and stored procedures/functions.
--   - Views actor_info and nicer_but_slower_film_list (use GROUP_CONCAT,
--     not directly portable to Oracle; LISTAGG used in the views we keep).
--   - staff.picture BLOB column.
--   - address.location GEOMETRY column.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

CREATE TABLE actor (
  actor_id    NUMBER(5)     GENERATED BY DEFAULT AS IDENTITY,
  first_name  VARCHAR2(45)  NOT NULL,
  last_name   VARCHAR2(45)  NOT NULL,
  last_update TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_actor PRIMARY KEY (actor_id)
);

CREATE TABLE country (
  country_id  NUMBER(5)     GENERATED BY DEFAULT AS IDENTITY,
  country     VARCHAR2(50)  NOT NULL,
  last_update TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_country PRIMARY KEY (country_id)
);

CREATE TABLE city (
  city_id     NUMBER(5)     GENERATED BY DEFAULT AS IDENTITY,
  city        VARCHAR2(50)  NOT NULL,
  country_id  NUMBER(5)     NOT NULL,
  last_update TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_city PRIMARY KEY (city_id)
);

CREATE TABLE address (
  address_id  NUMBER(5)     GENERATED BY DEFAULT AS IDENTITY,
  address     VARCHAR2(50)  NOT NULL,
  address2    VARCHAR2(50)  DEFAULT NULL,
  -- Oracle treats '' as NULL, and Sakila address data has rows with empty
  -- district/phone strings, so NOT NULL would reject them.
  district    VARCHAR2(20)  DEFAULT NULL,
  city_id     NUMBER(5)     NOT NULL,
  postal_code VARCHAR2(10)  DEFAULT NULL,
  phone       VARCHAR2(20)  DEFAULT NULL,
  -- location GEOMETRY column omitted.
  last_update TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_address PRIMARY KEY (address_id)
);

CREATE TABLE category (
  category_id NUMBER(3)     GENERATED BY DEFAULT AS IDENTITY,
  name        VARCHAR2(25)  NOT NULL,
  last_update TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (category_id)
);

CREATE TABLE language (
  language_id NUMBER(3)     GENERATED BY DEFAULT AS IDENTITY,
  name        CHAR(20)      NOT NULL,
  last_update TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_language PRIMARY KEY (language_id)
);

CREATE TABLE film (
  film_id              NUMBER(5)      GENERATED BY DEFAULT AS IDENTITY,
  title                VARCHAR2(128)  NOT NULL,
  -- VARCHAR2 (not CLOB) so views can GROUP BY description; Sakila data is well
  -- within Oracle's default 4000-byte VARCHAR2 limit.
  description          VARCHAR2(4000) DEFAULT NULL,
  release_year         NUMBER(4)      DEFAULT NULL,
  language_id          NUMBER(3)      NOT NULL,
  original_language_id NUMBER(3)      DEFAULT NULL,
  rental_duration      NUMBER(3)      DEFAULT 3 NOT NULL,
  rental_rate          NUMBER(4,2)    DEFAULT 4.99 NOT NULL,
  length               NUMBER(5)      DEFAULT NULL,
  replacement_cost     NUMBER(5,2)    DEFAULT 19.99 NOT NULL,
  rating               VARCHAR2(10)   DEFAULT 'G',
  -- special_features stored as comma-separated VARCHAR2 (no MySQL SET equivalent).
  special_features     VARCHAR2(100)  DEFAULT NULL,
  last_update          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_film PRIMARY KEY (film_id),
  CONSTRAINT chk_film_rating CHECK (rating IN ('G','PG','PG-13','R','NC-17'))
);

CREATE TABLE film_actor (
  actor_id    NUMBER(5)  NOT NULL,
  film_id     NUMBER(5)  NOT NULL,
  last_update TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_film_actor PRIMARY KEY (actor_id, film_id)
);

CREATE TABLE film_category (
  film_id     NUMBER(5)  NOT NULL,
  category_id NUMBER(3)  NOT NULL,
  last_update TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_film_category PRIMARY KEY (film_id, category_id)
);

CREATE TABLE inventory (
  inventory_id NUMBER(8)  GENERATED BY DEFAULT AS IDENTITY,
  film_id      NUMBER(5)  NOT NULL,
  store_id     NUMBER(3)  NOT NULL,
  last_update  TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_inventory PRIMARY KEY (inventory_id)
);

-- staff and store form a cycle (store.manager_staff_id -> staff,
-- staff.store_id -> store). Create both tables first, add FKs at the end.
CREATE TABLE staff (
  staff_id    NUMBER(3)     GENERATED BY DEFAULT AS IDENTITY,
  first_name  VARCHAR2(45)  NOT NULL,
  last_name   VARCHAR2(45)  NOT NULL,
  address_id  NUMBER(5)     NOT NULL,
  -- picture BLOB column omitted.
  email       VARCHAR2(50)  DEFAULT NULL,
  store_id    NUMBER(3)     NOT NULL,
  active      NUMBER(1)     DEFAULT 1 NOT NULL,
  username    VARCHAR2(16)  NOT NULL,
  password    VARCHAR2(40)  DEFAULT NULL,
  last_update TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_staff PRIMARY KEY (staff_id),
  CONSTRAINT chk_staff_active CHECK (active IN (0, 1))
);

CREATE TABLE store (
  store_id         NUMBER(3)  GENERATED BY DEFAULT AS IDENTITY,
  manager_staff_id NUMBER(3)  NOT NULL,
  address_id       NUMBER(5)  NOT NULL,
  last_update      TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_store PRIMARY KEY (store_id),
  CONSTRAINT uq_store_manager UNIQUE (manager_staff_id)
);

CREATE TABLE customer (
  customer_id NUMBER(5)     GENERATED BY DEFAULT AS IDENTITY,
  store_id    NUMBER(3)     NOT NULL,
  first_name  VARCHAR2(45)  NOT NULL,
  last_name   VARCHAR2(45)  NOT NULL,
  email       VARCHAR2(50)  DEFAULT NULL,
  address_id  NUMBER(5)     NOT NULL,
  active      NUMBER(1)     DEFAULT 1 NOT NULL,
  create_date TIMESTAMP     NOT NULL,
  last_update TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_customer PRIMARY KEY (customer_id),
  CONSTRAINT chk_customer_active CHECK (active IN (0, 1))
);

CREATE TABLE rental (
  rental_id    NUMBER(10)  GENERATED BY DEFAULT AS IDENTITY,
  rental_date  TIMESTAMP   NOT NULL,
  inventory_id NUMBER(8)   NOT NULL,
  customer_id  NUMBER(5)   NOT NULL,
  return_date  TIMESTAMP   DEFAULT NULL,
  staff_id     NUMBER(3)   NOT NULL,
  last_update  TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT pk_rental PRIMARY KEY (rental_id),
  CONSTRAINT uq_rental_unique UNIQUE (rental_date, inventory_id, customer_id)
);

CREATE TABLE payment (
  payment_id   NUMBER(5)    GENERATED BY DEFAULT AS IDENTITY,
  customer_id  NUMBER(5)    NOT NULL,
  staff_id     NUMBER(3)    NOT NULL,
  rental_id    NUMBER(10)   DEFAULT NULL,
  amount       NUMBER(5,2)  NOT NULL,
  payment_date TIMESTAMP    NOT NULL,
  last_update  TIMESTAMP    DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_payment PRIMARY KEY (payment_id)
);

-- ---------------------------------------------------------------------------
-- Secondary indexes
-- ---------------------------------------------------------------------------

CREATE INDEX idx_actor_last_name        ON actor (last_name);
CREATE INDEX idx_address_city_id        ON address (city_id);
CREATE INDEX idx_city_country_id        ON city (country_id);
CREATE INDEX idx_customer_store_id      ON customer (store_id);
CREATE INDEX idx_customer_address_id    ON customer (address_id);
CREATE INDEX idx_customer_last_name     ON customer (last_name);
CREATE INDEX idx_film_title             ON film (title);
CREATE INDEX idx_film_language_id       ON film (language_id);
CREATE INDEX idx_film_orig_language_id  ON film (original_language_id);
CREATE INDEX idx_film_actor_film        ON film_actor (film_id);
CREATE INDEX idx_inventory_film_id      ON inventory (film_id);
CREATE INDEX idx_inventory_store_film   ON inventory (store_id, film_id);
CREATE INDEX idx_payment_staff_id       ON payment (staff_id);
CREATE INDEX idx_payment_customer_id    ON payment (customer_id);
CREATE INDEX idx_rental_inventory_id    ON rental (inventory_id);
CREATE INDEX idx_rental_customer_id     ON rental (customer_id);
CREATE INDEX idx_rental_staff_id        ON rental (staff_id);
CREATE INDEX idx_staff_store_id         ON staff (store_id);
CREATE INDEX idx_staff_address_id       ON staff (address_id);
CREATE INDEX idx_store_address_id       ON store (address_id);

-- Foreign keys are NOT declared here. Sakila data is loaded in alphabetical
-- table order (the order MySQL's mysqldump emits), so child rows arrive
-- before parents. The FK constraints are added in 3-oracle-sakila-finalize.sql
-- after the data load, where the bulk-validation also doubles as a
-- referential-integrity check on the conversion.

-- ---------------------------------------------------------------------------
-- Views
-- ---------------------------------------------------------------------------

CREATE VIEW customer_list AS
SELECT cu.customer_id              AS id,
       cu.first_name || ' ' || cu.last_name AS name,
       a.address                   AS address,
       a.postal_code               AS zip_code,
       a.phone                     AS phone,
       city.city                   AS city,
       country.country             AS country,
       CASE WHEN cu.active = 1 THEN 'active' ELSE '' END AS notes,
       cu.store_id                 AS sid
FROM customer cu
JOIN address  a       ON cu.address_id = a.address_id
JOIN city             ON a.city_id     = city.city_id
JOIN country          ON city.country_id = country.country_id;

CREATE VIEW staff_list AS
SELECT s.staff_id                 AS id,
       s.first_name || ' ' || s.last_name AS name,
       a.address                  AS address,
       a.postal_code              AS zip_code,
       a.phone                    AS phone,
       city.city                  AS city,
       country.country            AS country,
       s.store_id                 AS sid
FROM staff s
JOIN address  a   ON s.address_id  = a.address_id
JOIN city         ON a.city_id     = city.city_id
JOIN country      ON city.country_id = country.country_id;

CREATE VIEW sales_by_store AS
SELECT c.city || ',' || cy.country         AS store,
       m.first_name || ' ' || m.last_name  AS manager,
       SUM(p.amount)                        AS total_sales
FROM payment   p
JOIN rental    r  ON p.rental_id    = r.rental_id
JOIN inventory i  ON r.inventory_id = i.inventory_id
JOIN store     s  ON i.store_id     = s.store_id
JOIN address   a  ON s.address_id   = a.address_id
JOIN city      c  ON a.city_id      = c.city_id
JOIN country   cy ON c.country_id   = cy.country_id
JOIN staff     m  ON s.manager_staff_id = m.staff_id
GROUP BY s.store_id, c.city, cy.country, m.first_name, m.last_name
ORDER BY cy.country, c.city;

CREATE VIEW sales_by_film_category AS
SELECT c.name         AS category,
       SUM(p.amount)  AS total_sales
FROM payment       p
JOIN rental        r  ON p.rental_id    = r.rental_id
JOIN inventory     i  ON r.inventory_id = i.inventory_id
JOIN film          f  ON i.film_id      = f.film_id
JOIN film_category fc ON f.film_id      = fc.film_id
JOIN category      c  ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY total_sales DESC;

CREATE VIEW film_list AS
SELECT film.film_id                AS fid,
       film.title                  AS title,
       film.description            AS description,
       category.name               AS category,
       film.rental_rate            AS price,
       film.length                 AS length,
       film.rating                 AS rating,
       LISTAGG(actor.first_name || ' ' || actor.last_name, ', ')
         WITHIN GROUP (ORDER BY actor.last_name, actor.first_name) AS actors
FROM category
LEFT JOIN film_category ON category.category_id = film_category.category_id
LEFT JOIN film          ON film_category.film_id = film.film_id
JOIN film_actor         ON film.film_id = film_actor.film_id
JOIN actor              ON film_actor.actor_id = actor.actor_id
GROUP BY film.film_id, film.title, film.description, category.name,
         film.rental_rate, film.length, film.rating;
