-- Sakila finalize: install foreign keys, realign identity high-water marks,
-- and verify expected row counts. Runs as the sakila app user on FREEPDB1.

-- --- Foreign keys -----------------------------------------------------------
-- Added after the data load (which arrives in alphabetical table order, so
-- child rows precede parents). Adding the FK after data is in place lets
-- Oracle's built-in validation pass also serve as a sanity check on the
-- converted dump.

ALTER TABLE city
  ADD CONSTRAINT fk_city_country
  FOREIGN KEY (country_id) REFERENCES country (country_id);

ALTER TABLE address
  ADD CONSTRAINT fk_address_city
  FOREIGN KEY (city_id) REFERENCES city (city_id);

ALTER TABLE customer
  ADD CONSTRAINT fk_customer_address
  FOREIGN KEY (address_id) REFERENCES address (address_id);

ALTER TABLE customer
  ADD CONSTRAINT fk_customer_store
  FOREIGN KEY (store_id) REFERENCES store (store_id);

ALTER TABLE film
  ADD CONSTRAINT fk_film_language
  FOREIGN KEY (language_id) REFERENCES language (language_id);

ALTER TABLE film
  ADD CONSTRAINT fk_film_language_original
  FOREIGN KEY (original_language_id) REFERENCES language (language_id);

ALTER TABLE film_actor
  ADD CONSTRAINT fk_film_actor_actor
  FOREIGN KEY (actor_id) REFERENCES actor (actor_id);

ALTER TABLE film_actor
  ADD CONSTRAINT fk_film_actor_film
  FOREIGN KEY (film_id) REFERENCES film (film_id);

ALTER TABLE film_category
  ADD CONSTRAINT fk_film_category_film
  FOREIGN KEY (film_id) REFERENCES film (film_id);

ALTER TABLE film_category
  ADD CONSTRAINT fk_film_category_category
  FOREIGN KEY (category_id) REFERENCES category (category_id);

ALTER TABLE inventory
  ADD CONSTRAINT fk_inventory_film
  FOREIGN KEY (film_id) REFERENCES film (film_id);

ALTER TABLE inventory
  ADD CONSTRAINT fk_inventory_store
  FOREIGN KEY (store_id) REFERENCES store (store_id);

ALTER TABLE staff
  ADD CONSTRAINT fk_staff_address
  FOREIGN KEY (address_id) REFERENCES address (address_id);

ALTER TABLE staff
  ADD CONSTRAINT fk_staff_store
  FOREIGN KEY (store_id) REFERENCES store (store_id);

ALTER TABLE store
  ADD CONSTRAINT fk_store_staff
  FOREIGN KEY (manager_staff_id) REFERENCES staff (staff_id);

ALTER TABLE store
  ADD CONSTRAINT fk_store_address
  FOREIGN KEY (address_id) REFERENCES address (address_id);

ALTER TABLE rental
  ADD CONSTRAINT fk_rental_inventory
  FOREIGN KEY (inventory_id) REFERENCES inventory (inventory_id);

ALTER TABLE rental
  ADD CONSTRAINT fk_rental_customer
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE rental
  ADD CONSTRAINT fk_rental_staff
  FOREIGN KEY (staff_id) REFERENCES staff (staff_id);

ALTER TABLE payment
  ADD CONSTRAINT fk_payment_customer
  FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE payment
  ADD CONSTRAINT fk_payment_staff
  FOREIGN KEY (staff_id) REFERENCES staff (staff_id);

ALTER TABLE payment
  ADD CONSTRAINT fk_payment_rental
  FOREIGN KEY (rental_id) REFERENCES rental (rental_id) ON DELETE SET NULL;

-- --- Realign identity columns -----------------------------------------------
-- Explicit-id INSERTs do not advance the underlying identity sequence, so
-- without this any subsequent INSERT that omits the id would collide with
-- existing rows. RESTART STARTS WITH MAX(id)+1 fixes that.
DECLARE
  PROCEDURE realign(p_table VARCHAR2, p_id_col VARCHAR2) IS
    v_next NUMBER;
  BEGIN
    EXECUTE IMMEDIATE
      'SELECT NVL(MAX(' || p_id_col || '),0)+1 FROM ' || p_table
      INTO v_next;
    EXECUTE IMMEDIATE
      'ALTER TABLE ' || p_table ||
      ' MODIFY ' || p_id_col || ' GENERATED BY DEFAULT AS IDENTITY (START WITH ' ||
      v_next || ')';
  END;
BEGIN
  realign('actor',     'actor_id');
  realign('address',   'address_id');
  realign('category',  'category_id');
  realign('city',      'city_id');
  realign('country',   'country_id');
  realign('customer',  'customer_id');
  realign('film',      'film_id');
  realign('inventory', 'inventory_id');
  realign('language',  'language_id');
  realign('payment',   'payment_id');
  realign('rental',    'rental_id');
  realign('staff',     'staff_id');
  realign('store',     'store_id');
END;
/

-- --- Row-count tripwire (build fails here if conversion drifted) ------------
DECLARE
  PROCEDURE assert_count(p_table VARCHAR2, p_expected NUMBER) IS
    v_got NUMBER;
  BEGIN
    EXECUTE IMMEDIATE 'SELECT COUNT(*) FROM ' || p_table INTO v_got;
    IF v_got <> p_expected THEN
      RAISE_APPLICATION_ERROR(
        -20001,
        'sakila row-count mismatch on ' || p_table ||
        ': expected ' || p_expected || ', got ' || v_got);
    END IF;
  END;
BEGIN
  assert_count('actor',     200);
  assert_count('address',   603);
  assert_count('category',  16);
  assert_count('city',      600);
  assert_count('country',   109);
  assert_count('customer',  599);
  assert_count('film',      1000);
  assert_count('film_actor', 5462);
  assert_count('film_category', 1000);
  assert_count('inventory', 4581);
  assert_count('language',  6);
  assert_count('payment',   16049);
  assert_count('rental',    16044);
  assert_count('staff',     2);
  assert_count('store',     2);
END;
/

SELECT 'sakiladb/oracle has successfully initialized.' AS sakiladb_completion_message
FROM dual;
