#!/usr/bin/env python3
"""Convert MySQL Sakila data dump to Oracle 23ai INSERTs.

- Strips MySQL preamble (SET, LOCK/UNLOCK, USE, COMMIT, /*!...*/).
- Drops the address.location GEOMETRY column.
- Carries staff.picture (Sakila's only BLOB): the inline INSERT keeps the
  column NULL (the ~36 KB hex blob exceeds Oracle's 4000-byte SQL string
  literal limit), then a trailing PL/SQL DBMS_LOB block reassembles the image
  from hex chunks and UPDATEs staff_id = 1.
- Skips the film_text table (omitted from our schema).
- Strips backticks from table names in INSERT statements.
- Emits a leading ALTER SESSION so MySQL's ISO timestamp string literals
  ('YYYY-MM-DD HH24:MI:SS') cast implicitly into TIMESTAMP/DATE columns.
- film.special_features stays as the comma-separated string MySQL emits;
  our schema stores it in VARCHAR2(100).

Usage:
    python3 convert_data.py mysql-sakila-data.sql 2-oracle-sakila-data.sql

Input file `mysql-sakila-data.sql` is the upstream MySQL Sakila data dump,
vendored into this repo so the build is self-contained.
"""

import re
import sys

MYSQL_PREAMBLE_PREFIXES = ("SET ", "USE ", "LOCK ", "UNLOCK ", "COMMIT")


def strip_address_geometry(line):
    # /*!50705 0xDEADBEEF,*/  →  ""  (the GEOMETRY column was preceded by ',')
    return re.sub(r'/\*!\d+ 0x[0-9A-Fa-f]+,\*/', '', line)


# The staff.picture hex blob, captured from the staff INSERT so the trailing
# DBMS_LOB block can reload it. Sakila has exactly one such image (staff_id = 1;
# staff_id = 2 is NULL), so a single module-level capture is sufficient.
captured_staff_picture_hex = None


def neutralize_staff_picture(line):
    # staff row layout (matches the Oracle schema column order):
    #   (id, first, last, address_id, picture, email, store_id, ...)
    # MySQL emits picture as either a hex BLOB (0xAB...) or NULL. Oracle cannot
    # take the ~36 KB hex as an inline literal (4000-byte limit), so replace the
    # blob with NULL here and stash the hex for the DBMS_LOB load emitted later.
    # The NULL picture on staff_id = 2 is left exactly as MySQL emits it.
    global captured_staff_picture_hex
    m = re.search(r',0x([0-9A-Fa-f]+),', line)
    if m:
        captured_staff_picture_hex = m.group(1)
        line = line[:m.start()] + ',NULL,' + line[m.end():]
    return line


def emit_staff_picture_load(f_out, hexstr):
    """Reassemble the staff.picture BLOB from hex chunks via DBMS_LOB.

    A single inline HEXTORAW would exceed Oracle's 4000-byte string-literal
    limit (the image is ~36 KB = ~72 KB of hex), and BLOB || BLOB is not valid
    in static SQL, so the image is built up with WRITEAPPEND over conservative
    chunks (1000 bytes each, well under every literal limit) and written to the
    staff row that was inserted above with picture NULL.
    """
    if len(hexstr) % 2 != 0:
        raise ValueError("staff.picture hex has an odd length")
    chunk = 2000  # hex chars => 1000 bytes per WRITEAPPEND, safely under 4000
    f_out.write(
        "\n-- --- staff.picture BLOB (staff_id = 1) --------------------------------\n"
        "-- Sakila's only binary column: a ~36 KB PNG. It exceeds Oracle's\n"
        "-- 4000-byte SQL string-literal limit, so it is reassembled from hex\n"
        "-- chunks with DBMS_LOB.WRITEAPPEND and written to the row inserted\n"
        "-- above (picture NULL). staff_id = 2 stays NULL, as in MySQL Sakila.\n"
        "-- Generated by convert_data.py; do not edit by hand.\n"
        "DECLARE\n"
        "  v_blob BLOB;\n"
        "BEGIN\n"
        "  DBMS_LOB.CREATETEMPORARY(v_blob, TRUE);\n")
    for i in range(0, len(hexstr), chunk):
        piece = hexstr[i:i + chunk]
        f_out.write(
            "  DBMS_LOB.WRITEAPPEND(v_blob, %d, HEXTORAW('%s'));\n"
            % (len(piece) // 2, piece))
    f_out.write(
        "  UPDATE staff SET picture = v_blob WHERE staff_id = 1;\n"
        "  DBMS_LOB.FREETEMPORARY(v_blob);\n"
        "END;\n"
        "/\n"
        "COMMIT;\n")


def strip_table_backticks(line):
    return re.sub(r'INSERT INTO `(\w+)`', r'INSERT INTO \1', line)


def main():
    if len(sys.argv) < 3:
        print("usage: convert_data.py <input-mysql-dump> <output-oracle-sql>",
              file=sys.stderr)
        sys.exit(1)

    input_file, output_file = sys.argv[1], sys.argv[2]

    current_table = None

    with open(input_file, 'r') as f_in, open(output_file, 'w') as f_out:
        f_out.write("-- Sakila Sample Database Data for Oracle 23ai\n")
        f_out.write("-- Converted from mysql-sakila-data.sql\n")
        f_out.write("-- Run as the sakila user against the SAKILA PDB.\n\n")

        # Allow blank lines inside long multi-row INSERTs without sqlplus
        # treating them as statement terminators.
        f_out.write("SET SQLBLANKLINES ON\n")
        # Make the MySQL ISO timestamp literals cast implicitly.
        f_out.write("ALTER SESSION SET NLS_TIMESTAMP_FORMAT='YYYY-MM-DD HH24:MI:SS';\n")
        f_out.write("ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS';\n\n")

        for line in f_in:
            stripped = line.strip()

            # Skip MySQL preamble + transaction control.
            if stripped.startswith(MYSQL_PREAMBLE_PREFIXES):
                continue

            # Skip MySQL conditional comment statements: /*!12345 ... */;
            if stripped.startswith('/*!') and stripped.endswith(';'):
                continue

            # Track which table we are currently emitting INSERTs for.
            m = re.match(r'-- Dumping data for table\s+`?(\w+)`?', stripped)
            if m:
                current_table = m.group(1)
                if current_table != 'film_text':
                    f_out.write(line)
                continue

            # Drop everything for the omitted film_text table.
            if current_table == 'film_text':
                continue

            if stripped.startswith('INSERT INTO'):
                line = strip_table_backticks(line)
                if current_table == 'staff':
                    line = neutralize_staff_picture(line)
                elif current_table == 'address':
                    line = strip_address_geometry(line)
                f_out.write(line)
            elif stripped.startswith('(') and current_table:
                # Continuation of a multi-row VALUES list.
                if current_table == 'staff':
                    line = neutralize_staff_picture(line)
                elif current_table == 'address':
                    line = strip_address_geometry(line)
                f_out.write(line)
            elif stripped.startswith('--') or stripped == '':
                f_out.write(line)
            # else: any other line is silently dropped (DELIMITER, etc.)

        f_out.write("\nCOMMIT;\n")

        # Reload staff.picture (dropped from the inline INSERT above) via a
        # DBMS_LOB block, now that the staff rows exist.
        if captured_staff_picture_hex is None:
            raise SystemExit("convert_data.py: staff.picture blob not found in input")
        emit_staff_picture_load(f_out, captured_staff_picture_hex)


if __name__ == '__main__':
    main()
